# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bomtique < Formula
  desc "Hand-authored SBOM toolkit: emit CycloneDX/SPDX SBOMs from curated Component Manifests."
  homepage "https://github.com/interlynk-io/bomtique"
  version "0.1.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/interlynk-io/bomtique/releases/download/v0.1.5/bomtique_0.1.5_Darwin_x86_64.tar.gz"
      sha256 "f151decb585d70da572b7f9cce7e19cada8baa6302a7f7bb98f53470b8adb24e"

      define_method(:install) do
        bin.install "bomtique"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/interlynk-io/bomtique/releases/download/v0.1.5/bomtique_0.1.5_Darwin_arm64.tar.gz"
      sha256 "f3ea3f8322462c9a90df68d6f51a8c1befade71c488c1fb6c02e998a9d03b09a"

      define_method(:install) do
        bin.install "bomtique"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/interlynk-io/bomtique/releases/download/v0.1.5/bomtique_0.1.5_Linux_x86_64.tar.gz"
      sha256 "db2f0b4e2b31a72487275117a80326045e553e249661e5c6c1d614ffe2e39ed4"
      define_method(:install) do
        bin.install "bomtique"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/interlynk-io/bomtique/releases/download/v0.1.5/bomtique_0.1.5_Linux_arm64.tar.gz"
      sha256 "f7c23531cf379bc7641971f5ed9ea41e09a187cd211b67950863683aacd5b6bd"
      define_method(:install) do
        bin.install "bomtique"
      end
    end
  end

  test do
    assert_match "bomtique", shell_output("#{bin}/bomtique --version")
  end
end
