# This file was generated by GoReleaser. DO NOT EDIT.
cask "lynk-mcp" do
  version "0.2.5"

  on_macos do
    on_intel do
      sha256 "9fb2d9e9391e29c770db650c2243053f45671ff1851d658707755d9f2361807b"
      url "https://github.com/interlynk-io/lynk-mcp/releases/download/v#{version}/lynk-mcp_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "05ea7f3daebf10c9615513da40067f638808ee3c87ba9595b53f51d7a7b9e3c7"
      url "https://github.com/interlynk-io/lynk-mcp/releases/download/v#{version}/lynk-mcp_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ef8ffa59ec9060f2f1bbe3898691c5d0b36f44009ea3ebdb324001697c543332"
      url "https://github.com/interlynk-io/lynk-mcp/releases/download/v#{version}/lynk-mcp_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8ccd230ab728b514ed38dede59c982c4a6a21092a1b01475a72a75492f0c420c"
      url "https://github.com/interlynk-io/lynk-mcp/releases/download/v#{version}/lynk-mcp_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "lynk-mcp"
  desc "MCP server for Lynk SBOM and vulnerability management"
  homepage "https://github.com/interlynk-io/lynk-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lynk-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lynk-mcp"]
    end
  end

  # No zap stanza required

end
