# This file was generated by GoReleaser. DO NOT EDIT.
cask "lynk-mcp" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "cb18d9372e78edd4322c9c5aaf68a46dd0eec7fd9a76cc3153a0badd875a802c"
      url "https://github.com/interlynk-io/lynk-mcp/releases/download/v#{version}/lynk-mcp_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "10275fb5b65ddc568e5ac0679146f596c8440b477da7a9f87c9bd302e4cc5956"
      url "https://github.com/interlynk-io/lynk-mcp/releases/download/v#{version}/lynk-mcp_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "06e4b487bcaedbdcd3c873d99f477e7db6858a9006cac006a82d85a2674f64f1"
      url "https://github.com/interlynk-io/lynk-mcp/releases/download/v#{version}/lynk-mcp_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "cdb444a07c47946b2cadc20bdad6610224fd36387917ba64c9e55944b272592a"
      url "https://github.com/interlynk-io/lynk-mcp/releases/download/v#{version}/lynk-mcp_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "lynk-mcp"
  desc "MCP server for Lynk SBOM and vulnerability management"
  homepage "https://github.com/interlynk-io/lynk-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lynk-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lynk-mcp"]
    end
  end

  # No zap stanza required

end
