# This file was generated by GoReleaser. DO NOT EDIT.
cask "lynk-mcp" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "de127d8cbadeb398ab1084ded28114e2e254e325030590e8d9a10d833f583713"
      url "https://github.com/interlynk-io/lynk-mcp/releases/download/v#{version}/lynk-mcp_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6b766be64e6cb2dc5c94b40ef9ad0391857eec485de10ffc6bf468ffd959ccf1"
      url "https://github.com/interlynk-io/lynk-mcp/releases/download/v#{version}/lynk-mcp_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "58cbd19c6a40c6e068ad56ccdae008918350b277f04cf12e37afb38d16a0d7f5"
      url "https://github.com/interlynk-io/lynk-mcp/releases/download/v#{version}/lynk-mcp_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "543f591d2e12a7b31a67c12c4bcf46afe8f0efb09abebdf93eacdf1b571435ed"
      url "https://github.com/interlynk-io/lynk-mcp/releases/download/v#{version}/lynk-mcp_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "lynk-mcp"
  desc "MCP server for Lynk SBOM and vulnerability management"
  homepage "https://github.com/interlynk-io/lynk-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lynk-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lynk-mcp"]
    end
  end

  # No zap stanza required

end
