# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bomtique < Formula
  desc "Hand-authored SBOM toolkit: emit CycloneDX/SPDX SBOMs from curated Component Manifests."
  homepage "https://github.com/interlynk-io/bomtique"
  version "0.1.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/interlynk-io/bomtique/releases/download/v0.1.6/bomtique_0.1.6_Darwin_x86_64.tar.gz"
      sha256 "17e4df09a0f5567aaa5eb1658cd3349b5f7eddb9bea33c35bf0f14c3c2b29125"

      define_method(:install) do
        bin.install "bomtique"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/interlynk-io/bomtique/releases/download/v0.1.6/bomtique_0.1.6_Darwin_arm64.tar.gz"
      sha256 "e3d75b22344e0306c6bfcf6fc54d9c37d7c65b596b5bcf95aa6c8229cc173134"

      define_method(:install) do
        bin.install "bomtique"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/interlynk-io/bomtique/releases/download/v0.1.6/bomtique_0.1.6_Linux_x86_64.tar.gz"
      sha256 "0e904e993313bde7732b4b9b3c74806da5d31763c741225bc3c94d1ab328d683"
      define_method(:install) do
        bin.install "bomtique"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/interlynk-io/bomtique/releases/download/v0.1.6/bomtique_0.1.6_Linux_arm64.tar.gz"
      sha256 "38c233784e4f6266f9aeffac735ac2107dd03fc7ffe959c9447d77adad7de45a"
      define_method(:install) do
        bin.install "bomtique"
      end
    end
  end

  test do
    assert_match "bomtique", shell_output("#{bin}/bomtique --version")
  end
end
