# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LynkMcp < Formula
  desc "MCP server for AI-powered SBOM and vulnerability management"
  homepage "https://github.com/interlynk-io/lynk-mcp"
  version "0.1.5"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_intel do
      url "https://github.com/interlynk-io/lynk-mcp/releases/download/v#{version}/lynk-mcp_#{version}_Darwin_x86_64.tar.gz"
      sha256 "7ff8b0de982c570612d8d7dfab2e87c79f332029140cf933473e63cb31989172"
    end

    on_arm do
      url "https://github.com/interlynk-io/lynk-mcp/releases/download/v#{version}/lynk-mcp_#{version}_Darwin_arm64.tar.gz"
      sha256 "e9ed9b5c27942408772120b8e3b5d43c1d84c9ce7f74e866c6d989831a6219d0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/interlynk-io/lynk-mcp/releases/download/v#{version}/lynk-mcp_#{version}_Linux_x86_64.tar.gz"
      sha256 "bc1eaa5000b15c560c7b82f4fd990e0a733382bfd4caaa939936254b2f7209aa"
    end

    on_arm do
      url "https://github.com/interlynk-io/lynk-mcp/releases/download/v#{version}/lynk-mcp_#{version}_Linux_arm64.tar.gz"
      sha256 "916912fdece41a388b6fdaccd2f4e6539b001412c4ef6a380848deadbafb29e6"
    end
  end

  def install
    bin.install "lynk-mcp"
    generate_completions_from_executable(bin/"lynk-mcp", "completion")
  end

  test do
    assert_match "lynk-mcp", shell_output("#{bin}/lynk-mcp version")
    assert_match "MCP server", shell_output("#{bin}/lynk-mcp --help")
  end
end
