# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LynkMcp < Formula
  desc "MCP server for AI-powered SBOM and vulnerability management"
  homepage "https://github.com/interlynk-io/lynk-mcp"
  version "0.2.6"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_intel do
      url "https://github.com/interlynk-io/lynk-mcp/releases/download/v#{version}/lynk-mcp_#{version}_Darwin_x86_64.tar.gz"
      sha256 "ecc4b44764dae26adbe5ee8e727be5876fcee01b690534e48819076f86e888e5"
    end

    on_arm do
      url "https://github.com/interlynk-io/lynk-mcp/releases/download/v#{version}/lynk-mcp_#{version}_Darwin_arm64.tar.gz"
      sha256 "acc32ec7c73b6a3facbc1e74db0c836b7562865266c329b8050b409950bacf83"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/interlynk-io/lynk-mcp/releases/download/v#{version}/lynk-mcp_#{version}_Linux_x86_64.tar.gz"
      sha256 "1d818b7659b8f5a33ca1e3a4b5ef1392029e1a69ce9ec07e733890e4bfca03b9"
    end

    on_arm do
      url "https://github.com/interlynk-io/lynk-mcp/releases/download/v#{version}/lynk-mcp_#{version}_Linux_arm64.tar.gz"
      sha256 "81ce6f3170cd2caa06747a2b1430b715647d508cc180303101dabe7d277f5f59"
    end
  end

  def install
    bin.install "lynk-mcp"
    generate_completions_from_executable(bin/"lynk-mcp", "completion")
  end

  test do
    assert_match "lynk-mcp", shell_output("#{bin}/lynk-mcp version")
    assert_match "MCP server", shell_output("#{bin}/lynk-mcp --help")
  end
end
