# Copyright 2023 Interlynk.io
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbomex < Formula
  desc "sbomex is a command line utility to help query and pull from Interlynk public SBOM"
  homepage "https://github.com/interlynk-io/sbomex"
  version "0.0.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/interlynk-io/sbomex/releases/download/v0.0.3/sbomex-darwin-amd64", :using => :nounzip
      sha256 "9546707130adb82e9a78b12fbeff6cb512d7c7a100253db25cfa3eb0f147b545"

      def install
        bin.install "sbomex-darwin-amd64" => "sbomex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/interlynk-io/sbomex/releases/download/v0.0.3/sbomex-darwin-arm64", :using => :nounzip
      sha256 "4c218bb45f8e9f24223665ec67f797b7bf1f42a817899da067a61cf912c5a373"

      def install
        bin.install "sbomex-darwin-arm64" => "sbomex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/interlynk-io/sbomex/releases/download/v0.0.3/sbomex-linux-amd64", :using => :nounzip
      sha256 "83f718bfd9a8e572733947974b6d574aed8df4a99737f1ec0694c18a4dd7edc9"

      def install
        bin.install "sbomex-linux-amd64" => "sbomex"
      end
    end
  end
end
