# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbommv < Formula
  desc "SBOM Move - Automate build and transfer of SBOMs across systems"
  homepage "https://github.com/interlynk-io/sbommv"
  version "v1.0.2"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_intel do
      url "https://github.com/interlynk-io/sbommv/releases/download/#{version}/sbommv-darwin-amd64", using: :nounzip
      sha256 "6591213fa6a178144acc1753b8f0b86c8593a37f80b6ae8008ecf1b1c7f94ce5"
    end

    on_arm do
      url "https://github.com/interlynk-io/sbommv/releases/download/#{version}/sbommv-darwin-arm64", using: :nounzip
      sha256 "5bb8b7b3a604d59c2fae472a598d88e4777df8c86cbcadde3b4c1c479f1edcac"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/interlynk-io/sbommv/releases/download/#{version}/sbommv-linux-amd64", using: :nounzip
      sha256 "b318f70547f2d4edb9d3e532353824c737cf73ced18c5ae966df56de983898d5"
    end

    on_arm do
      url "https://github.com/interlynk-io/sbommv/releases/download/#{version}/sbommv-linux-arm64", using: :nounzip
      sha256 "47154f07689291738a33b7f4003dc2d0cee98030d31cddf783c512fe80e95218"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    chmod "+x", "sbommv-#{os}-#{arch}"
    bin.install "sbommv-#{os}-#{arch}" => "sbommv"
    generate_completions_from_executable(bin/"sbommv", "completion")
  end

  test do
    assert_match "sbommv", shell_output("#{bin}/sbommv version")
    assert_match "transfer", shell_output("#{bin}/sbommv --help")
  end
end
