# Copyright 2023 Interlynk.io
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbomgr < Formula
  desc "SBOM Grep - Search through SBOMs"
  homepage "https://github.com/interlynk-io/sbomgr"
  version "v0.0.12"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/interlynk-io/sbomgr/releases/download/v0.0.12/sbomgr-darwin-arm64", :using => :nounzip
      sha256 "a5f89ee315ddcc620c80207e54d7146b468222aaf224bd4ea1f84a1a5a1f461b"

      def install
        bin.install "sbomgr-darwin-arm64" => "sbomgr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/interlynk-io/sbomgr/releases/download/v0.0.12/sbomgr-darwin-amd64", :using => :nounzip
      sha256 "bee5992198b03a85e91e227f187b7b81bb7f7bee2edf14026921cb91a2ccccf4"

      def install
        bin.install "sbomgr-darwin-amd64" => "sbomgr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/interlynk-io/sbomgr/releases/download/v0.0.12/sbomgr-linux-arm64", :using => :nounzip
      sha256 "3d5db98a30e28441ba134812bd5069f7ec2e3ac19ceb6f23a15cdb767e714aa5"

      def install
        bin.install "sbomgr-linux-arm64" => "sbomgr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/interlynk-io/sbomgr/releases/download/v0.0.12/sbomgr-linux-amd64", :using => :nounzip
      sha256 "3d9652f41fbf22e95eff6d291ee8c801c4a647ba3bb2a29eea95902269841ee9"

      def install
        bin.install "sbomgr-linux-amd64" => "sbomgr"
      end
    end
  end

  test do
    system "#{bin}/sbomgr" "version"
  end
end
