# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbomqs < Formula
  desc "sbomqs: The Comprehensive SBOM Quality & Compliance Tool"
  homepage "https://github.com/interlynk-io/sbomqs"
  version "2.1.2"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_intel do
      url "https://github.com/interlynk-io/sbomqs/releases/download/v#{version}/sbomqs_#{version}_Darwin_x86_64.tar.gz"
      sha256 "669315b2e008ec935ca9d04c980ac05f747e0a7bd1acf3c767ab017fe47a70d3"
    end

    on_arm do
      url "https://github.com/interlynk-io/sbomqs/releases/download/v#{version}/sbomqs_#{version}_Darwin_arm64.tar.gz"
      sha256 "cef45fcbdf12954cde0ff87c3740a0681d05e90d8c0cbee2e48e5e62b05d1c20"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/interlynk-io/sbomqs/releases/download/v#{version}/sbomqs_#{version}_Linux_x86_64.tar.gz"
      sha256 "451c800019c81059f86eac2c1344c57572b3436e7e0ffeaa076459d195a39ab8"
    end

    on_arm do
      url "https://github.com/interlynk-io/sbomqs/releases/download/v#{version}/sbomqs_#{version}_Linux_arm64.tar.gz"
      sha256 "5aec2aec04610a76347301f6ce837c71e82001b26c27d9cd05c47f72a0ed9aa1"
    end
  end

  def install
    bin.install "sbomqs"
    generate_completions_from_executable(bin/"sbomqs", "completion")
  end

  test do
    assert_match "sbomqs", shell_output("#{bin}/sbomqs version")
    assert_match "Quality score", shell_output("#{bin}/sbomqs --help")
  end
end
