# Copyright 2023 Interlynk.io
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbomex < Formula
  desc "sbomex is a command line utility to help query and pull from Interlynk public SBOM"
  homepage "https://github.com/interlynk-io/sbomex"
  version "v0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/interlynk-io/sbomex/releases/download/v0.1.0/sbomex-darwin-amd64", :using => :nounzip
      sha256 "86f5735c5d0f083f952db87ba9233fb77b3290d766a72ef7b24c805360e3ed93"

      def install
        bin.install "sbomex-darwin-amd64" => "sbomex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/interlynk-io/sbomex/releases/download/v0.1.0/sbomex-darwin-arm64", :using => :nounzip
      sha256 "14c36bd8f98689bca18d931f6e0e6acae174bd40549ffb80b6bc820eef27a327"

      def install
        bin.install "sbomex-darwin-arm64" => "sbomex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/interlynk-io/sbomex/releases/download/v0.1.0/sbomex-linux-arm64", :using => :nounzip
      sha256 "a1e46aff23abb2300befc74c24f8240ccda2c0a5fabc68efb302f91a0fc4c1ae"

      def install
        bin.install "sbomex-linux-arm64" => "sbomex"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/interlynk-io/sbomex/releases/download/v0.1.0/sbomex-linux-amd64", :using => :nounzip
      sha256 "3340a317532155e9322522f24e11d80914e722bfc4a78dd1dcda156d2f779e84"

      def install
        bin.install "sbomex-linux-amd64" => "sbomex"
      end
    end
  end
end
