# Copyright 2023 Interlynk.io
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbomasm < Formula
  desc "SBOM Assembler - Assembler for your SBOMs"
  homepage "https://github.com/interlynk-io/sbomasm"
  version "v0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/interlynk-io/sbomasm/releases/download/v0.0.1/sbomasm-darwin-arm64", :using => :nounzip
      sha256 "60f9a000f7827c68aa64eec8b6cb3b601fda4dba2e3b0792a084a0ab7a6ed3e4"

      def install
        bin.install "sbomasm-darwin-arm64" => "sbomasm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/interlynk-io/sbomasm/releases/download/v0.0.1/sbomasm-darwin-amd64", :using => :nounzip
      sha256 "82d0bb66532f13481d6f9d72b6e13672cf9b61ca7957e699ad47e282971b8f37"

      def install
        bin.install "sbomasm-darwin-amd64" => "sbomasm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/interlynk-io/sbomasm/releases/download/v0.0.1/sbomasm-linux-arm64", :using => :nounzip
      sha256 "d15e3ae40c74d728d62efc8db97988142f5bc96ebd964a0b47fa7aae9c97423d"

      def install
        bin.install "sbomasm-linux-arm64" => "sbomasm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/interlynk-io/sbomasm/releases/download/v0.0.1/sbomasm-linux-amd64", :using => :nounzip
      sha256 "1d88bd6891e58d654363cc4febd00f4fc909324d20b34e0bf76b576596cee3da"

      def install
        bin.install "sbomasm-linux-amd64" => "sbomasm"
      end
    end
  end

  test do
    system "#{bin}/sbomasm" "version"
  end
end
