# Copyright 2023 Interlynk.io
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbomgr < Formula
  desc "SBOM Grep - Search through SBOMs"
  homepage "https://github.com/interlynk-io/sbomgr"
  version "v0.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/interlynk-io/sbomgr/releases/download/v0.0.2/sbomgr-darwin-arm64", :using => :nounzip
      sha256 "93979e93cc27a8ade93d225084974001e31422204402171ee935b9ddf5a2c783"

      def install
        bin.install "sbomgr-darwin-arm64" => "sbomgr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/interlynk-io/sbomgr/releases/download/v0.0.2/sbomgr-darwin-amd64", :using => :nounzip
      sha256 "9c0412a1f0988efd2c9fef648796d8406dba9dabf9e9cf4d182a00737fb0877d"

      def install
        bin.install "sbomgr-darwin-amd64" => "sbomgr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/interlynk-io/sbomgr/releases/download/v0.0.2/sbomgr-linux-arm64", :using => :nounzip
      sha256 "3035d540d8f7636317fad159cc564c096bd68db22578f928b03a612f40d4ab9b"

      def install
        bin.install "sbomgr-linux-arm64" => "sbomgr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/interlynk-io/sbomgr/releases/download/v0.0.2/sbomgr-linux-amd64", :using => :nounzip
      sha256 "31196e330781b3e50b52a78ba29f1ac3d526c75da438aee45fcba098934c4af0"

      def install
        bin.install "sbomgr-linux-amd64" => "sbomgr"
      end
    end
  end

  test do
    system "#{bin}/sbomgr" "version"
  end
end
