# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbomqs < Formula
  desc "sbomqs: The Comprehensive SBOM Quality & Compliance Tool"
  homepage "https://github.com/interlynk-io/sbomqs"
  version "2.0.6"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_intel do
      url "https://github.com/interlynk-io/sbomqs/releases/download/v#{version}/sbomqs_#{version}_Darwin_x86_64.tar.gz"
      sha256 "a3eb9a02d11990ac8110617881dc05538e9da5f07b963c2f284fafc859b67202"
    end

    on_arm do
      url "https://github.com/interlynk-io/sbomqs/releases/download/v#{version}/sbomqs_#{version}_Darwin_arm64.tar.gz"
      sha256 "6d0177f942e5bca9172d681b66c34a8bb47a820f37989af704b7b9e23b965fe4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/interlynk-io/sbomqs/releases/download/v#{version}/sbomqs_#{version}_Linux_x86_64.tar.gz"
      sha256 "a1e9bbf4d6506237fded89d627e540270c1663aa0479d0ad751a81fa0f769fe9"
    end

    on_arm do
      url "https://github.com/interlynk-io/sbomqs/releases/download/v#{version}/sbomqs_#{version}_Linux_arm64.tar.gz"
      sha256 "c4529fdd72d07bf60a5f533c02b857f87df9eb56f1ba464326bf86174642b8e9"
    end
  end

  def install
    bin.install "sbomqs"
    generate_completions_from_executable(bin/"sbomqs", "completion")
  end

  test do
    assert_match "sbomqs", shell_output("#{bin}/sbomqs version")
    assert_match "Quality score", shell_output("#{bin}/sbomqs --help")
  end
end
