# Copyright 2025 Interlynk.io
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbomasm < Formula
  desc "sbomasm: The Complete SBOM Management Toolkit"
  homepage "https://github.com/interlynk-io/sbomasm"
  version "v2.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/interlynk-io/sbomasm/releases/download/v2.0.0/sbomasm_2.0.0_Darwin_arm64.tar.gz"
      sha256 "866c1e511ebd127e4f9b629d127cb9462e3394725defd93361ddc9dec08be7eb"

      def install
        bin.install "sbomasm"
      end
    end

    if Hardware::CPU.intel?
      url "https://github.com/interlynk-io/sbomasm/releases/download/v2.0.0/sbomasm_2.0.0_Darwin_x86_64.tar.gz"
      sha256 "5a2a161fa20cdd0331f0658f14204abeb5b659ef0ffaa2a5e8895a6c84b24ce9"

      def install
        bin.install "sbomasm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/interlynk-io/sbomasm/releases/download/v2.0.0/sbomasm_2.0.0_Linux_arm64.tar.gz"
      sha256 "ee152e201a142656d896a927079bb7451993ec0f9d03125416ff965a4e26e2d2"

      def install
        bin.install "sbomasm"
      end
    end

    if Hardware::CPU.intel?
      url "https://github.com/interlynk-io/sbomasm/releases/download/v2.0.0/sbomasm_2.0.0_Linux_x86_64.tar.gz"
      sha256 "3fdefca7ede51728f371a060cb8aa8f4f088829d2ff3b7aee41e66aa22e64672"

      def install
        bin.install "sbomasm"
      end
    end
  end

  test do
    system "#{bin}/sbomasm", "version"
  end
end
