# Copyright 2025 Interlynk.io
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbomqs < Formula
  desc 'sbomqs: The Comprehensive SBOM Quality & Compliance Tool'
  homepage 'https://github.com/interlynk-io/sbomqs'
  version 'v2.0.2'
  license 'Apache-2.0'

  on_macos do
    if Hardware::CPU.intel?
      url 'https://github.com/interlynk-io/sbomqs/releases/download/v2.0.2/sbomqs_2.0.2_Darwin_x86_64.tar.gz'
      sha256 'fcca18f721fd6ca33b21c4640076b92b2e3cad66a1adfe42571b8bff6f619f55'

      def install
        bin.install 'sbomqs'
      end
    end

    if Hardware::CPU.arm?
      url 'https://github.com/interlynk-io/sbomqs/releases/download/v2.0.2/sbomqs_2.0.2_Darwin_arm64.tar.gz'
      sha256 'dbd7e91f34dfe1b72e39fecdc1fc5c22a482a2770ed72f58795a32abde76f7b2'

      def install
        bin.install 'sbomqs'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url 'https://github.com/interlynk-io/sbomqs/releases/download/v2.0.2/sbomqs_2.0.2_Linux_x86_64.tar.gz'
      sha256 'f4f6bf5368ea116c113cf94bbd0858e407c6f119cdd803174ab7fcd9aeb75d8c'

      def install
        bin.install 'sbomqs'
      end
    end

    if Hardware::CPU.arm?
      url 'https://github.com/interlynk-io/sbomqs/releases/download/v2.0.2/sbomqs_2.0.2_Linux_arm64.tar.gz'
      sha256 'ded2b27864b2a2640af1dbf62215c9b940d1899499da1a90bdc3f21d5a3d1043'

      def install
        bin.install 'sbomqs'
      end
    end
  end

  test do
    system "#{bin}/sbomqs", 'version'
  end
end
