# Copyright 2023 Interlynk.io
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbomgr < Formula
  desc "SBOM Grep - Search through SBOMs"
  homepage "https://github.com/interlynk-io/sbomgr"
  version "v0.0.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/interlynk-io/sbomgr/releases/download/v0.0.4/sbomgr-darwin-arm64", :using => :nounzip
      sha256 "bf0007ffa6fc70fca1925c733f779867c1e6871fba6689e0b6d66a153ece1ff4"

      def install
        bin.install "sbomgr-darwin-arm64" => "sbomgr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/interlynk-io/sbomgr/releases/download/v0.0.4/sbomgr-darwin-amd64", :using => :nounzip
      sha256 "14df79b479a302dc3750fc8696ebe58030cee1d7ae6d5b817321dbcbf68a10e5"

      def install
        bin.install "sbomgr-darwin-amd64" => "sbomgr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/interlynk-io/sbomgr/releases/download/v0.0.4/sbomgr-linux-arm64", :using => :nounzip
      sha256 "409ac7913d4183a15bfaa2ed05d0353556d9e809f9c5958d059d935303ddd05a"

      def install
        bin.install "sbomgr-linux-arm64" => "sbomgr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/interlynk-io/sbomgr/releases/download/v0.0.4/sbomgr-linux-amd64", :using => :nounzip
      sha256 "389dce9310512503eb611e8dd93768414111220b0e121569eb72a009d0e76c78"

      def install
        bin.install "sbomgr-linux-amd64" => "sbomgr"
      end
    end
  end

  test do
    system "#{bin}/sbomgr" "version"
  end
end
