# Copyright 2025 Interlynk.io
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbomasm < Formula
  desc 'sbomasm: The Complete SBOM Management Toolkit'
  homepage 'https://github.com/interlynk-io/sbomasm'
  version 'v2.0.1'
  license 'Apache-2.0'

  on_macos do
    if Hardware::CPU.arm?
      url 'https://github.com/interlynk-io/sbomasm/releases/download/v2.0.1/sbomasm_2.0.1_Darwin_arm64.tar.gz'
      sha256 'a7499558b6189bcbcd98bcfb43abd16f1377505332fba2236449718b27366df3'

      def install
        bin.install 'sbomasm'
      end
    end

    if Hardware::CPU.intel?
      url 'https://github.com/interlynk-io/sbomasm/releases/download/v2.0.1/sbomasm_2.0.1_Darwin_x86_64.tar.gz'
      sha256 'ae71861d7f6a10e9313ed291b60fd9dabd39d21725607d241264f523a016dc96'

      def install
        bin.install 'sbomasm'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url 'https://github.com/interlynk-io/sbomasm/releases/download/v2.0.1/sbomasm_2.0.1_Linux_arm64.tar.gz'
      sha256 'ae90f7f275a5480b2631c34cdb01b88bec67f0f5443ce99d59442153fe2a6982'

      def install
        bin.install 'sbomasm'
      end
    end

    if Hardware::CPU.intel?
      url 'https://github.com/interlynk-io/sbomasm/releases/download/v2.0.1/sbomasm_2.0.1_Linux_x86_64.tar.gz'
      sha256 'c2c026100b5407fe29fb04f2b4af3a999c53599d8718ff3e03fe276854be5c97'

      def install
        bin.install 'sbomasm'
      end
    end
  end

  test do
    system "#{bin}/sbomasm", 'version'
  end
end
