# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbommv < Formula
  desc "SBOM Move - Automate build and transfer of SBOMs across systems"
  homepage "https://github.com/interlynk-io/sbommv"
  version "v1.0.0"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_intel do
      url "https://github.com/interlynk-io/sbommv/releases/download/#{version}/sbommv-darwin-amd64", using: :nounzip
      sha256 "1f1ee2dd6186eb59b5409bd70bb4519a572440652fe8dde9fca6aa245f7ab374"
    end

    on_arm do
      url "https://github.com/interlynk-io/sbommv/releases/download/#{version}/sbommv-darwin-arm64", using: :nounzip
      sha256 "225f534de093064658d7f6bedea7f02945184174ad13e3706bba73d7a6b86f56"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/interlynk-io/sbommv/releases/download/#{version}/sbommv-linux-amd64", using: :nounzip
      sha256 "8981471265cfcf129633dacfd26ed6ce872cb9da3d9ba9f4edc02d375f898f35"
    end

    on_arm do
      url "https://github.com/interlynk-io/sbommv/releases/download/#{version}/sbommv-linux-arm64", using: :nounzip
      sha256 "cbe63b303fbee882ccce253ba0ea25b5aecff07955d840343045d7260d0daaec"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "sbommv-#{os}-#{arch}" => "sbommv"
    generate_completions_from_executable(bin/"sbommv", "completion")
  end

  test do
    assert_match "sbommv", shell_output("#{bin}/sbommv version")
    assert_match "transfer", shell_output("#{bin}/sbommv --help")
  end
end
